version: "3.8"

services:
  web:
    build: .
    depends_on:
      - chrome
      - db
    env_file:
      - config/docker.env
    ports:
      - "3000:3000"
    volumes:
      - "./:/app/"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
  db:
    image: postgres:13
    env_file:
      - config/docker.env
    ports:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  chrome:
    image: selenium/standalone-chrome:3.141.59-zirconium # this version should match that of the selenium-webdriver gem (see Gemfile)
    volumes:
      - /dev/shm:/dev/shm
volumes:
  # Volume to hold the Postgres database on the host system
  data:
